version: '3.3'
services:
  elasticsearch:
    image: elasticsearch:2
    container_name: websitesearch
    ports:
      - "9200:9200"
  web:
    build:
      context: .
      dockerfile: .dockerfile
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./:/usr/src/app
    links:
     - postgres
     - elasticsearch
    ports:
     - 80:80
    environment:
      - DATABASE_URL=postgres://postgres:@postgres:5432/postgres
      - SECRET_KEY=enter-a-long-unguessable-string-here
      - ELASTICSEARCH_URL=http://websitesearch:9200
      - DJANGO_SETTINGS_MODULE=iati.settings.dev
  postgres:
    image: postgres:9.6
    ports:
     - 5432:5432
