version: "3.3"
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile_deploy
    environment:
      - SECRET_KEY
      - DATABASE_NAME
      - DATABASE_USER
      - DATABASE_PASS
      - DATABASE_HOST
      - DATABASE_PORT
      - APPLICATIONINSIGHTS_CONNECTION_STRING
      - AZURE_ACCOUNT_NAME
      - AZURE_ACCOUNT_KEY
      - AZURE_CONTAINER
    ports:
      - 5000:5000
