version: "3.3"
services:

  postgres:
    image: postgres:9.6
    ports:
      - 5432:5432
  web:
    build:
      context: .
    environment:
      - DATABASE_URL=postgres://postgres:@postgres:5432/postgres
      - SECRET_KEY=enter-a-long-unguessable-string-here
      - ELASTICSEARCH_URL=http://localhost:9200
      - DJANGO_SETTINGS_MODULE=iati.settings.dev
      - RABBITMQ_URL=amqp://localhost:5672
    links:
      - postgres
    ports:
      - 5000:5000
    volumes:
      - ./:/usr/src/app
