web:
  build: .
  dockerfile: .dockerfile
  command: python manage.py runserver 0.0.0.0:80 --settings=iati.settings.dev
  volumes:
    - ./:/usr/src/app
  links:
   - postgres
  ports:
   - 80:80
  environment:
    - DATABASE_URL=postgres://postgres:@postgres:5432/postgres
    - SECRET_KEY=enter-a-long-unguessable-string-here
postgres:
  image: postgres:9.6
  ports:
   - 5432
