version: "3.3"
services:

  web:
    build:
      context: .
    environment:
      - DJANGO_SETTINGS_MODULE=iati.settings.production
      - ELASTICSEARCH_URL=http://localhost:9200
      - RABBITMQ_URL=amqp://localhost:5672
      - SECRET_KEY
      - DATABASE_URL
      - APPLICATIONINSIGHTS_CONNECTION_STRING
      - AZURE_ACCOUNT_NAME
      - AZURE_ACCOUNT_KEY
      - AZURE_CONTAINER
    ports:
      - 5000:5000
    volumes:
      - ./:/usr/src/app
