
version: '3.3'
services:
  elk:
    image: sebp/elk:es235_l234_k454
    ports:
      - "5601:5601"
      - "5044:5044"
      - "9200:9200"
  web:
    build:
      context: .
      dockerfile: .dockerfile
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./:/usr/src/app
    links:
     - postgres
     - elk
     - rabbitmq
    ports:
     - 80:80
    environment:
      - DATABASE_URL=postgres://postgres:@postgres:5432/postgres
      - SECRET_KEY=enter-a-long-unguessable-string-here
      - ELASTICSEARCH_URL=http://elk:9200
      - DJANGO_SETTINGS_MODULE=iati.settings.dev
  postgres:
    image: postgres:9.6
    ports:
     - 5432:5432
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 15672:15672
    restart: always
