services:

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.25
    environment:
      - ES_SETTING_XPACK_SECURITY_ENABLED=false
      - ES_SETTING_DISCOVERY_TYPE=single-node
    ports:
      - 9200:9200

  web:
    build:
      context: .
    environment:
      - DATABASE_URL=postgres://postgres:@postgres:5432/postgres
      - SECRET_KEY=enter-a-long-unguessable-string-here
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - DJANGO_SETTINGS_MODULE=iati.settings.dev
      - GUNICORN_WORKERS=1
      - GITHUB_TOKEN
      - RECAPTCHA_PUBLIC_KEY
      - RECAPTCHA_PRIVATE_KEY
      - DEBUG_SERVER
      - COMPRESS_ENABLED
      - SENTRY_DSN
    # I'm not sure why these links are needed; I thought Docker defaults would just do this for us but without it
    # the Web container can't see the others.
    links:
      - postgres:postgres
      - elasticsearch:elasticsearch
    ports:
      - 5000:5000
    volumes:
      - ./:/usr/src/app

networks:
  default:
    name: iati-standard-website
