# Generated by Django 3.2.4 on 2023-04-25 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20230127_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='newscategory',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='newscategory',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='newscategory',
            name='name_pt',
        ),
        migrations.RemoveField(
            model_name='newsindexpage',
            name='excerpt_en',
        ),
        migrations.RemoveField(
            model_name='newsindexpage',
            name='excerpt_es',
        ),
        migrations.RemoveField(
            model_name='newsindexpage',
            name='excerpt_fr',
        ),
        migrations.RemoveField(
            model_name='newsindexpage',
            name='excerpt_pt',
        ),
        migrations.RemoveField(
            model_name='newsindexpage',
            name='heading_en',
        ),
        migrations.RemoveField(
            model_name='newsindexpage',
            name='heading_es',
        ),
        migrations.RemoveField(
            model_name='newsindexpage',
            name='heading_fr',
        ),
        migrations.RemoveField(
            model_name='newsindexpage',
            name='heading_pt',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='content_editor_en',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='content_editor_es',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='content_editor_fr',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='content_editor_pt',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='excerpt_en',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='excerpt_es',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='excerpt_fr',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='excerpt_pt',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='heading_en',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='heading_es',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='heading_fr',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='heading_pt',
        ),
    ]
