# Generated by Django 3.2.4 on 2023-04-25 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20230120_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='contact_type_en',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='contact_type_es',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='contact_type_fr',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='contact_type_pt',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='content_editor_en',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='content_editor_es',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='content_editor_fr',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='content_editor_pt',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='excerpt_en',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='excerpt_es',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='excerpt_fr',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='excerpt_pt',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='heading_en',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='heading_es',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='heading_fr',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='heading_pt',
        ),
    ]
