# Generated by Django 2.0.8 on 2019-04-24 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guidance_and_support', '0003_social_media'),
        ('guidance_and_support', '0003_community_page'),
    ]

    operations = [
    ]
