# Generated by Django 2.0.3 on 2018-03-29 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('home', '0003_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
