# Generated by Django 2.0.8 on 2019-03-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180626_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='fixed_page_type',
            field=models.CharField(blank=True, choices=[('privacy', 'Privacy'), ('terms', 'Terms and conditions'), ('trans', 'Translation FAQs')], max_length=7, null=True),
        ),
    ]
