# Generated by Django 2.0.8 on 2019-03-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190311_0832'),
        ('home', '0005_auto_20190315_0947'),
    ]

    operations = [
    ]
