# Generated by Django 2.0.8 on 2019-06-03 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_merge_20190320_0931'),
        ('home', '0007_social_media'),
    ]

    operations = [
    ]
