# Generated by Django 2.0.5 on 2018-09-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180626_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='featured_event',
            field=models.BooleanField(default=False),
        ),
    ]
