# Generated by Django 2.0.3 on 2018-04-04 19:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('events', '0002_auto_20180404_1841'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventIndex',
            new_name='EventIndexPage',
        ),
        migrations.RenameModel(
            old_name='Event',
            new_name='EventPage',
        ),
    ]
