# Generated by Django 2.0.4 on 2018-04-05 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180404_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventindexpage',
            old_name='excerpt_sp',
            new_name='excerpt_es',
        ),
        migrations.RenameField(
            model_name='eventindexpage',
            old_name='heading_sp',
            new_name='heading_es',
        ),
        migrations.RenameField(
            model_name='eventpage',
            old_name='additional_information_sp',
            new_name='additional_information_es',
        ),
        migrations.RenameField(
            model_name='eventpage',
            old_name='description_sp',
            new_name='description_es',
        ),
        migrations.RenameField(
            model_name='eventpage',
            old_name='heading_sp',
            new_name='heading_es',
        ),
        migrations.RenameField(
            model_name='eventpage',
            old_name='subheading_sp',
            new_name='subheading_es',
        ),
        migrations.RenameField(
            model_name='eventtype',
            old_name='name_sp',
            new_name='name_es',
        ),
    ]
