# Generated by Django 2.0.4 on 2018-04-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20180405_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='title_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='title_fr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
