# Generated by Django 2.0.4 on 2018-04-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20180405_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventindexpage',
            name='title_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventindexpage',
            name='title_fr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
