# Generated by Django 2.0.4 on 2018-04-06 17:40

from django.db import migrations, models
import home.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20180406_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventindexpage',
            name='excerpt_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventindexpage',
            name='excerpt_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventindexpage',
            name='excerpt_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventindexpage',
            name='excerpt_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventindexpage',
            name='heading_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventindexpage',
            name='heading_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventindexpage',
            name='heading_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventindexpage',
            name='heading_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='additional_information_en',
            field=wagtail.core.fields.StreamField((('h2', wagtail.core.blocks.CharBlock(classname='title', icon='title')), ('h3', wagtail.core.blocks.CharBlock(classname='title', icon='title')), ('h4', wagtail.core.blocks.CharBlock(classname='title', icon='title')), ('intro', wagtail.core.blocks.RichTextBlock(icon='pilcrow')), ('paragraph', wagtail.core.blocks.RichTextBlock(icon='pilcrow')), ('endnote', wagtail.core.blocks.StructBlock((('number', wagtail.core.blocks.CharBlock()), ('citation', wagtail.core.blocks.RichTextBlock(required=False))))), ('aligned_image', wagtail.core.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.RichTextBlock(required=False)), ('alignment', home.models.ImageFormatChoiceBlock())), icon='image', label='Aligned image')), ('pullquote', wagtail.core.blocks.StructBlock((('quote', wagtail.core.blocks.TextBlock('quote title')), ('attribution', wagtail.core.blocks.CharBlock())))), ('aligned_html', wagtail.core.blocks.StructBlock((('html', wagtail.core.blocks.RawHTMLBlock()), ('alignment', home.models.HTMLAlignmentChoiceBlock())), icon='code', label='Raw HTML')), ('document', wagtail.documents.blocks.DocumentChooserBlock(icon='doc-full-inverse'))), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='additional_information_es',
            field=wagtail.core.fields.StreamField((('h2', wagtail.core.blocks.CharBlock(classname='title', icon='title')), ('h3', wagtail.core.blocks.CharBlock(classname='title', icon='title')), ('h4', wagtail.core.blocks.CharBlock(classname='title', icon='title')), ('intro', wagtail.core.blocks.RichTextBlock(icon='pilcrow')), ('paragraph', wagtail.core.blocks.RichTextBlock(icon='pilcrow')), ('endnote', wagtail.core.blocks.StructBlock((('number', wagtail.core.blocks.CharBlock()), ('citation', wagtail.core.blocks.RichTextBlock(required=False))))), ('aligned_image', wagtail.core.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.RichTextBlock(required=False)), ('alignment', home.models.ImageFormatChoiceBlock())), icon='image', label='Aligned image')), ('pullquote', wagtail.core.blocks.StructBlock((('quote', wagtail.core.blocks.TextBlock('quote title')), ('attribution', wagtail.core.blocks.CharBlock())))), ('aligned_html', wagtail.core.blocks.StructBlock((('html', wagtail.core.blocks.RawHTMLBlock()), ('alignment', home.models.HTMLAlignmentChoiceBlock())), icon='code', label='Raw HTML')), ('document', wagtail.documents.blocks.DocumentChooserBlock(icon='doc-full-inverse'))), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='additional_information_fr',
            field=wagtail.core.fields.StreamField((('h2', wagtail.core.blocks.CharBlock(classname='title', icon='title')), ('h3', wagtail.core.blocks.CharBlock(classname='title', icon='title')), ('h4', wagtail.core.blocks.CharBlock(classname='title', icon='title')), ('intro', wagtail.core.blocks.RichTextBlock(icon='pilcrow')), ('paragraph', wagtail.core.blocks.RichTextBlock(icon='pilcrow')), ('endnote', wagtail.core.blocks.StructBlock((('number', wagtail.core.blocks.CharBlock()), ('citation', wagtail.core.blocks.RichTextBlock(required=False))))), ('aligned_image', wagtail.core.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.RichTextBlock(required=False)), ('alignment', home.models.ImageFormatChoiceBlock())), icon='image', label='Aligned image')), ('pullquote', wagtail.core.blocks.StructBlock((('quote', wagtail.core.blocks.TextBlock('quote title')), ('attribution', wagtail.core.blocks.CharBlock())))), ('aligned_html', wagtail.core.blocks.StructBlock((('html', wagtail.core.blocks.RawHTMLBlock()), ('alignment', home.models.HTMLAlignmentChoiceBlock())), icon='code', label='Raw HTML')), ('document', wagtail.documents.blocks.DocumentChooserBlock(icon='doc-full-inverse'))), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='additional_information_pt',
            field=wagtail.core.fields.StreamField((('h2', wagtail.core.blocks.CharBlock(classname='title', icon='title')), ('h3', wagtail.core.blocks.CharBlock(classname='title', icon='title')), ('h4', wagtail.core.blocks.CharBlock(classname='title', icon='title')), ('intro', wagtail.core.blocks.RichTextBlock(icon='pilcrow')), ('paragraph', wagtail.core.blocks.RichTextBlock(icon='pilcrow')), ('endnote', wagtail.core.blocks.StructBlock((('number', wagtail.core.blocks.CharBlock()), ('citation', wagtail.core.blocks.RichTextBlock(required=False))))), ('aligned_image', wagtail.core.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.RichTextBlock(required=False)), ('alignment', home.models.ImageFormatChoiceBlock())), icon='image', label='Aligned image')), ('pullquote', wagtail.core.blocks.StructBlock((('quote', wagtail.core.blocks.TextBlock('quote title')), ('attribution', wagtail.core.blocks.CharBlock())))), ('aligned_html', wagtail.core.blocks.StructBlock((('html', wagtail.core.blocks.RawHTMLBlock()), ('alignment', home.models.HTMLAlignmentChoiceBlock())), icon='code', label='Raw HTML')), ('document', wagtail.documents.blocks.DocumentChooserBlock(icon='doc-full-inverse'))), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='heading_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='heading_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='heading_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='heading_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='subheading_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='subheading_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='subheading_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='subheading_pt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
