# Generated by Django 2.0.4 on 2018-04-11 19:35

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('events', '0011_auto_20180411_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='documents',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='wagtaildocs.Document'),
        ),
    ]
