# Generated by Django 2.0.4 on 2018-04-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_eventpage_feed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='slug',
            field=models.SlugField(default='slug', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventtype',
            name='slug_en',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='slug_es',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='slug_fr',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='slug_pt',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
