# Generated by Django 2.0.4 on 2018-04-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20180412_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='slug_es',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='slug_fr',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='slug_pt',
        ),
    ]
