# Generated by Django 3.2.4 on 2021-08-27 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_auto_20200428_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalnotice',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='globalnotice',
            name='content_es',
        ),
        migrations.RemoveField(
            model_name='globalnotice',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='globalnotice',
            name='content_pt',
        ),
        migrations.RemoveField(
            model_name='pagenotice',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='pagenotice',
            name='content_es',
        ),
        migrations.RemoveField(
            model_name='pagenotice',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='pagenotice',
            name='content_pt',
        ),
    ]
