# Generated by Django 2.2.9 on 2020-02-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the category', max_length=100)),
                ('title_en', models.CharField(help_text='The title of the category', max_length=100, null=True)),
                ('title_fr', models.CharField(help_text='The title of the category', max_length=100, null=True)),
                ('title_es', models.CharField(help_text='The title of the category', max_length=100, null=True)),
                ('title_pt', models.CharField(help_text='The title of the category', max_length=100, null=True)),
                ('slug', models.SlugField(help_text='The slug must be unqiue for this category', max_length=100, unique=True)),
                ('slug_en', models.SlugField(help_text='The slug must be unqiue for this category', max_length=100, null=True, unique=True)),
                ('slug_fr', models.SlugField(help_text='The slug must be unqiue for this category', max_length=100, null=True, unique=True)),
                ('slug_es', models.SlugField(help_text='The slug must be unqiue for this category', max_length=100, null=True, unique=True)),
                ('slug_pt', models.SlugField(help_text='The slug must be unqiue for this category', max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Constituency',
            },
        ),
    ]
