# Generated by Django 2.2.9 on 2020-03-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constituency',
            options={'verbose_name': 'Constituency', 'verbose_name_plural': 'Constituencies'},
        ),
        migrations.AlterField(
            model_name='constituency',
            name='slug',
            field=models.SlugField(help_text='The slug must be unique for this category', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='constituency',
            name='slug_en',
            field=models.SlugField(help_text='The slug must be unique for this category', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='constituency',
            name='slug_es',
            field=models.SlugField(help_text='The slug must be unique for this category', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='constituency',
            name='slug_fr',
            field=models.SlugField(help_text='The slug must be unique for this category', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='constituency',
            name='slug_pt',
            field=models.SlugField(help_text='The slug must be unique for this category', max_length=100, null=True, unique=True),
        ),
    ]
