# Generated by Django 3.2.4 on 2021-08-27 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies', '0002_auto_20200302_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constituency',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='constituency',
            name='slug_es',
        ),
        migrations.RemoveField(
            model_name='constituency',
            name='slug_fr',
        ),
        migrations.RemoveField(
            model_name='constituency',
            name='slug_pt',
        ),
        migrations.RemoveField(
            model_name='constituency',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='constituency',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='constituency',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='constituency',
            name='title_pt',
        ),
    ]
