# Generated by Django 2.0.8 on 2019-03-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_merge_20190319_1153'),
        ('home', '0005_auto_20190208_1652'),
    ]

    operations = [
    ]
