# Generated by Django 2.2.9 on 2020-02-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_merge_20190603_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='header_video',
            field=models.URLField(blank=True, help_text='Optional: video embed URL for page header', max_length=255),
        ),
    ]
