# Generated by Django 2.2.9 on 2020-02-14 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_header_video'),
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='testimonial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='testimonials.Testimonial'),
        ),
    ]
