# Generated by Django 2.2.9 on 2020-02-17 16:47

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0010_homepage_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_iati_description',
            field=models.TextField(default='', help_text='Description for the about IATI section'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_iati_description_en',
            field=models.TextField(help_text='Description for the about IATI section', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_iati_description_es',
            field=models.TextField(help_text='Description for the about IATI section', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_iati_description_fr',
            field=models.TextField(help_text='Description for the about IATI section', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_iati_description_pt',
            field=models.TextField(help_text='Description for the about IATI section', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_iati_link_label',
            field=models.CharField(default='', help_text='Link label for the about IATI section', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_iati_link_label_en',
            field=models.CharField(help_text='Link label for the about IATI section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_iati_link_label_es',
            field=models.CharField(help_text='Link label for the about IATI section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_iati_link_label_fr',
            field=models.CharField(help_text='Link label for the about IATI section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_iati_link_label_pt',
            field=models.CharField(help_text='Link label for the about IATI section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_iati_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_iati_title',
            field=models.CharField(default='', help_text='Title for the about IATI section', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_iati_title_en',
            field=models.CharField(help_text='Title for the about IATI section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_iati_title_es',
            field=models.CharField(help_text='Title for the about IATI section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_iati_title_fr',
            field=models.CharField(help_text='Title for the about IATI section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_iati_title_pt',
            field=models.CharField(help_text='Title for the about IATI section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_iati_video',
            field=models.URLField(default='', help_text='Video embed URL for the about IATI section', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_iati_video_en',
            field=models.URLField(help_text='Video embed URL for the about IATI section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_iati_video_es',
            field=models.URLField(help_text='Video embed URL for the about IATI section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_iati_video_fr',
            field=models.URLField(help_text='Video embed URL for the about IATI section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_iati_video_pt',
            field=models.URLField(help_text='Video embed URL for the about IATI section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='activities_description',
            field=models.CharField(default='', help_text='Description for the activities statistics section', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='activities_description_en',
            field=models.CharField(help_text='Description for the activities statistics section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='activities_description_es',
            field=models.CharField(help_text='Description for the activities statistics section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='activities_description_fr',
            field=models.CharField(help_text='Description for the activities statistics section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='activities_description_pt',
            field=models.CharField(help_text='Description for the activities statistics section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='getting_started_title',
            field=models.CharField(default='', help_text='Title for the getting started section', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='getting_started_title_en',
            field=models.CharField(help_text='Title for the getting started section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='getting_started_title_es',
            field=models.CharField(help_text='Title for the getting started section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='getting_started_title_fr',
            field=models.CharField(help_text='Title for the getting started section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='getting_started_title_pt',
            field=models.CharField(help_text='Title for the getting started section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_video_en',
            field=models.URLField(blank=True, help_text='Optional: video embed URL for page header', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_video_es',
            field=models.URLField(blank=True, help_text='Optional: video embed URL for page header', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_video_fr',
            field=models.URLField(blank=True, help_text='Optional: video embed URL for page header', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_video_pt',
            field=models.URLField(blank=True, help_text='Optional: video embed URL for page header', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='iati_in_action_description',
            field=models.TextField(blank=True, help_text='Optional: description for the IATI in action section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='iati_in_action_description_en',
            field=models.TextField(blank=True, help_text='Optional: description for the IATI in action section', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='iati_in_action_description_es',
            field=models.TextField(blank=True, help_text='Optional: description for the IATI in action section', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='iati_in_action_description_fr',
            field=models.TextField(blank=True, help_text='Optional: description for the IATI in action section', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='iati_in_action_description_pt',
            field=models.TextField(blank=True, help_text='Optional: description for the IATI in action section', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='iati_in_action_title',
            field=models.CharField(default='', help_text='Title for the IATI in action section', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='iati_in_action_title_en',
            field=models.CharField(help_text='Title for the IATI in action section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='iati_in_action_title_es',
            field=models.CharField(help_text='Title for the IATI in action section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='iati_in_action_title_fr',
            field=models.CharField(help_text='Title for the IATI in action section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='iati_in_action_title_pt',
            field=models.CharField(help_text='Title for the IATI in action section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='iati_tools_title',
            field=models.CharField(default='', help_text='Title for the IATI tools section', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='iati_tools_title_description',
            field=models.TextField(blank=True, help_text='Optional: description for the IATI tools section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='iati_tools_title_description_en',
            field=models.TextField(blank=True, help_text='Optional: description for the IATI tools section', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='iati_tools_title_description_es',
            field=models.TextField(blank=True, help_text='Optional: description for the IATI tools section', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='iati_tools_title_description_fr',
            field=models.TextField(blank=True, help_text='Optional: description for the IATI tools section', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='iati_tools_title_description_pt',
            field=models.TextField(blank=True, help_text='Optional: description for the IATI tools section', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='iati_tools_title_en',
            field=models.CharField(help_text='Title for the IATI tools section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='iati_tools_title_es',
            field=models.CharField(help_text='Title for the IATI tools section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='iati_tools_title_fr',
            field=models.CharField(help_text='Title for the IATI tools section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='iati_tools_title_pt',
            field=models.CharField(help_text='Title for the IATI tools section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='latest_news_link_label',
            field=models.CharField(default='', help_text='Label for the view all news button', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='latest_news_link_label_en',
            field=models.CharField(help_text='Label for the view all news button', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='latest_news_link_label_es',
            field=models.CharField(help_text='Label for the view all news button', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='latest_news_link_label_fr',
            field=models.CharField(help_text='Label for the view all news button', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='latest_news_link_label_pt',
            field=models.CharField(help_text='Label for the view all news button', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='latest_news_title',
            field=models.CharField(default='', help_text='Title for the latest new section', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='latest_news_title_en',
            field=models.CharField(help_text='Title for the latest new section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='latest_news_title_es',
            field=models.CharField(help_text='Title for the latest new section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='latest_news_title_fr',
            field=models.CharField(help_text='Title for the latest new section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='latest_news_title_pt',
            field=models.CharField(help_text='Title for the latest new section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='latest_news_tweets_title',
            field=models.CharField(default='', help_text='Title for the latest news Twitter section', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='latest_news_tweets_title_en',
            field=models.CharField(help_text='Title for the latest news Twitter section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='latest_news_tweets_title_es',
            field=models.CharField(help_text='Title for the latest news Twitter section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='latest_news_tweets_title_fr',
            field=models.CharField(help_text='Title for the latest news Twitter section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='latest_news_tweets_title_pt',
            field=models.CharField(help_text='Title for the latest news Twitter section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='organisations_description',
            field=models.CharField(default='', help_text='Description for the organisations statistics section', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='organisations_description_en',
            field=models.CharField(help_text='Description for the organisations statistics section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='organisations_description_es',
            field=models.CharField(help_text='Description for the organisations statistics section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='organisations_description_fr',
            field=models.CharField(help_text='Description for the organisations statistics section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='organisations_description_pt',
            field=models.CharField(help_text='Description for the organisations statistics section', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='IATIToolsItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('item', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='iati_tools_items', to='home.HomePage')),
                ('page', models.ForeignKey(help_text='Page link for the item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IATIInActionItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, help_text='Optional: title for the item. Defaults to the selected page title if left blank', max_length=255)),
                ('title_en', models.CharField(blank=True, help_text='Optional: title for the item. Defaults to the selected page title if left blank', max_length=255, null=True)),
                ('title_fr', models.CharField(blank=True, help_text='Optional: title for the item. Defaults to the selected page title if left blank', max_length=255, null=True)),
                ('title_es', models.CharField(blank=True, help_text='Optional: title for the item. Defaults to the selected page title if left blank', max_length=255, null=True)),
                ('title_pt', models.CharField(blank=True, help_text='Optional: title for the item. Defaults to the selected page title if left blank', max_length=255, null=True)),
                ('description', models.CharField(blank=True, help_text='Optional: description for the item. Defaults to the selected page excerpt if left blank', max_length=255)),
                ('description_en', models.CharField(blank=True, help_text='Optional: description for the item. Defaults to the selected page excerpt if left blank', max_length=255, null=True)),
                ('description_fr', models.CharField(blank=True, help_text='Optional: description for the item. Defaults to the selected page excerpt if left blank', max_length=255, null=True)),
                ('description_es', models.CharField(blank=True, help_text='Optional: description for the item. Defaults to the selected page excerpt if left blank', max_length=255, null=True)),
                ('description_pt', models.CharField(blank=True, help_text='Optional: description for the item. Defaults to the selected page excerpt if left blank', max_length=255, null=True)),
                ('item', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='iati_in_action_items', to='home.HomePage')),
                ('page', models.ForeignKey(help_text='Page link for the item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IATIInActionFeaturedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, help_text='Optional: title for the item. Defaults to the selected page title if left blank', max_length=255)),
                ('title_en', models.CharField(blank=True, help_text='Optional: title for the item. Defaults to the selected page title if left blank', max_length=255, null=True)),
                ('title_fr', models.CharField(blank=True, help_text='Optional: title for the item. Defaults to the selected page title if left blank', max_length=255, null=True)),
                ('title_es', models.CharField(blank=True, help_text='Optional: title for the item. Defaults to the selected page title if left blank', max_length=255, null=True)),
                ('title_pt', models.CharField(blank=True, help_text='Optional: title for the item. Defaults to the selected page title if left blank', max_length=255, null=True)),
                ('description', models.CharField(blank=True, help_text='Optional: description for the item. Defaults to the selected page excerpt if left blank', max_length=255)),
                ('description_en', models.CharField(blank=True, help_text='Optional: description for the item. Defaults to the selected page excerpt if left blank', max_length=255, null=True)),
                ('description_fr', models.CharField(blank=True, help_text='Optional: description for the item. Defaults to the selected page excerpt if left blank', max_length=255, null=True)),
                ('description_es', models.CharField(blank=True, help_text='Optional: description for the item. Defaults to the selected page excerpt if left blank', max_length=255, null=True)),
                ('description_pt', models.CharField(blank=True, help_text='Optional: description for the item. Defaults to the selected page excerpt if left blank', max_length=255, null=True)),
                ('quote', models.CharField(blank=True, help_text='Optional: quote for the item', max_length=255)),
                ('quote_en', models.CharField(blank=True, help_text='Optional: quote for the item', max_length=255, null=True)),
                ('quote_fr', models.CharField(blank=True, help_text='Optional: quote for the item', max_length=255, null=True)),
                ('quote_es', models.CharField(blank=True, help_text='Optional: quote for the item', max_length=255, null=True)),
                ('quote_pt', models.CharField(blank=True, help_text='Optional: quote for the item', max_length=255, null=True)),
                ('quotee', models.CharField(blank=True, help_text='Optional: the source of the quote', max_length=255)),
                ('quotee_en', models.CharField(blank=True, help_text='Optional: the source of the quote', max_length=255, null=True)),
                ('quotee_fr', models.CharField(blank=True, help_text='Optional: the source of the quote', max_length=255, null=True)),
                ('quotee_es', models.CharField(blank=True, help_text='Optional: the source of the quote', max_length=255, null=True)),
                ('quotee_pt', models.CharField(blank=True, help_text='Optional: the source of the quote', max_length=255, null=True)),
                ('image', models.ForeignKey(blank=True, help_text='Optional: image for the item. Defaults to the selected page image if left blank', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('item', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='iati_in_action_featured_item', to='home.HomePage')),
                ('page', models.ForeignKey(help_text='Page link for the item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GettingStartedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(help_text='Title for the item', max_length=255)),
                ('title_en', models.CharField(help_text='Title for the item', max_length=255, null=True)),
                ('title_fr', models.CharField(help_text='Title for the item', max_length=255, null=True)),
                ('title_es', models.CharField(help_text='Title for the item', max_length=255, null=True)),
                ('title_pt', models.CharField(help_text='Title for the item', max_length=255, null=True)),
                ('description', models.CharField(help_text='Description for the item', max_length=255)),
                ('description_en', models.CharField(help_text='Description for the item', max_length=255, null=True)),
                ('description_fr', models.CharField(help_text='Description for the item', max_length=255, null=True)),
                ('description_es', models.CharField(help_text='Description for the item', max_length=255, null=True)),
                ('description_pt', models.CharField(help_text='Description for the item', max_length=255, null=True)),
                ('link_label', models.CharField(help_text='Link label for the item', max_length=255)),
                ('link_label_en', models.CharField(help_text='Link label for the item', max_length=255, null=True)),
                ('link_label_fr', models.CharField(help_text='Link label for the item', max_length=255, null=True)),
                ('link_label_es', models.CharField(help_text='Link label for the item', max_length=255, null=True)),
                ('link_label_pt', models.CharField(help_text='Link label for the item', max_length=255, null=True)),
                ('image', models.ForeignKey(help_text='Image for the item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('item', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='getting_started_items', to='home.HomePage')),
                ('page', models.ForeignKey(help_text='Page link for the item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
