# Generated by Django 2.2.9 on 2020-02-21 14:37

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0003_auto_20200220_1424'),
        ('home', '0013_auto_20200221_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('item', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonial_items', to='home.HomePage')),
                ('testimonial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='testimonials.Testimonial')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
