# Generated by Django 2.2.9 on 2020-03-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_latestnewsitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_iati_video',
            field=models.URLField(blank=True, help_text='Optional: video embed URL for the about IATI section', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_iati_video_en',
            field=models.URLField(blank=True, help_text='Optional: video embed URL for the about IATI section', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_iati_video_es',
            field=models.URLField(blank=True, help_text='Optional: video embed URL for the about IATI section', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_iati_video_fr',
            field=models.URLField(blank=True, help_text='Optional: video embed URL for the about IATI section', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_iati_video_pt',
            field=models.URLField(blank=True, help_text='Optional: video embed URL for the about IATI section', max_length=255, null=True),
        ),
    ]
