# Generated by Django 2.2.12 on 2020-07-20 15:33

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('home', '0019_auto_20200515_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpamSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spam_threshold', home.models.MinMaxFloat(default=0.0, help_text='Automatically delete Zendesk tickets equal to or below this threshold. 0.0 indicates spam, 1.0 indicates human.')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
