# Generated by Django 4.2.18 on 2025-06-10 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('home', '0024_auto_20230120_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='case_studies_link_label',
            field=models.CharField(default='FIND OUT MORE', help_text='Link label for the IATI case studies section', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='case_studies_link_label_en',
            field=models.CharField(default='FIND OUT MORE', help_text='Link label for the IATI case studies section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='case_studies_link_label_es',
            field=models.CharField(default='FIND OUT MORE', help_text='Link label for the IATI case studies section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='case_studies_link_label_fr',
            field=models.CharField(default='FIND OUT MORE', help_text='Link label for the IATI case studies section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='case_studies_link_label_pt',
            field=models.CharField(default='FIND OUT MORE', help_text='Link label for the IATI case studies section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='case_studies_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
