# Generated by Django 3.2.4 on 2023-04-28 14:34

from django.db import migrations
from wagtail.core.models import BootstrapTranslatableModel


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20230428_1433'),
    ]

    # Add one operation for each model to bootstrap here
    # Note: Only include models that are in the same app!
    operations = [
        BootstrapTranslatableModel('home.GettingStartedItems'),
    ]
