# Generated by Django 3.2.4 on 2023-04-28 17:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('home', '0027_auto_20230428_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gettingstarteditems',
            name='locale',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
        ),
        migrations.AlterField(
            model_name='gettingstarteditems',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='gettingstarteditems',
            unique_together={('translation_key', 'locale')},
        ),
    ]
