# Generated by Django 3.2.4 on 2023-05-02 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('home', '0028_auto_20230428_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='iatiinactionfeatureditems',
            name='locale',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
        ),
        migrations.AddField(
            model_name='iatiinactionfeatureditems',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
