# Generated by Django 3.2.4 on 2023-05-02 12:20

from django.db import migrations
from wagtail.core.models import BootstrapTranslatableModel
from home import inlines


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20230502_1219'),
    ]

    operations = [
        BootstrapTranslatableModel('home.IATIInActionFeaturedItems'),
    ]
