# Generated by Django 3.2.4 on 2023-05-03 13:09

from django.db import migrations
from wagtail.core.models import BootstrapTranslatableModel


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20230503_1309'),
    ]

    operations = [
        BootstrapTranslatableModel('home.IATIToolsItems'),
    ]
