# Generated by Django 2.0.8 on 2019-04-23 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailimages', '0019_delete_filter'),
        ('guidance_and_support', '0002_guidanceandsupportpage_header_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('heading_en', models.CharField(blank=True, max_length=255, null=True)),
                ('heading_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('heading_es', models.CharField(blank=True, max_length=255, null=True)),
                ('heading_pt', models.CharField(blank=True, max_length=255, null=True)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('excerpt_en', models.TextField(blank=True, null=True)),
                ('excerpt_fr', models.TextField(blank=True, null=True)),
                ('excerpt_es', models.TextField(blank=True, null=True)),
                ('excerpt_pt', models.TextField(blank=True, null=True)),
                ('text_box', models.TextField(blank=True, help_text='A small ammount of text describing the community page.', max_length=255, null=True)),
                ('text_box_en', models.TextField(blank=True, help_text='A small ammount of text describing the community page.', max_length=255, null=True)),
                ('text_box_fr', models.TextField(blank=True, help_text='A small ammount of text describing the community page.', max_length=255, null=True)),
                ('text_box_es', models.TextField(blank=True, help_text='A small ammount of text describing the community page.', max_length=255, null=True)),
                ('text_box_pt', models.TextField(blank=True, help_text='A small ammount of text describing the community page.', max_length=255, null=True)),
                ('button_link_text', models.CharField(blank=True, help_text='The text to appear on the button of the community page.', max_length=255, null=True)),
                ('button_link_text_en', models.CharField(blank=True, help_text='The text to appear on the button of the community page.', max_length=255, null=True)),
                ('button_link_text_fr', models.CharField(blank=True, help_text='The text to appear on the button of the community page.', max_length=255, null=True)),
                ('button_link_text_es', models.CharField(blank=True, help_text='The text to appear on the button of the community page.', max_length=255, null=True)),
                ('button_link_text_pt', models.CharField(blank=True, help_text='The text to appear on the button of the community page.', max_length=255, null=True)),
                ('button_url', models.URLField(blank=True, help_text='The url for the community page being linked', null=True)),
                ('header_image', models.ForeignKey(blank=True, help_text='This is the image that will appear in the header banner at the top of the page. If no image is added a placeholder image will be used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
