# Generated by Django 2.0.12 on 2020-01-07 14:32

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('guidance_and_support', '0005_communitypage_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidancepage',
            name='captchakey',
            field=models.CharField(blank=True, default=settings.RECAPTCHA_PUBLIC_KEY, max_length=255, null=True),
        ),
    ]
