# Generated by Django 2.2.12 on 2020-06-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_standard', '0003_auto_20200512_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardguidanceindexpage',
            name='excerpt_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standardguidanceindexpage',
            name='excerpt_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standardguidanceindexpage',
            name='excerpt_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standardguidanceindexpage',
            name='excerpt_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standardguidanceindexpage',
            name='heading_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='standardguidanceindexpage',
            name='heading_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='standardguidanceindexpage',
            name='heading_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='standardguidanceindexpage',
            name='heading_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
