# Generated by Django 2.2.12 on 2020-06-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_standard', '0004_auto_20200603_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardguidanceindexpage',
            name='button_link_text',
            field=models.CharField(blank=True, help_text='Button text to be shown on Guidance and Support page', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='standardguidanceindexpage',
            name='button_link_text_en',
            field=models.CharField(blank=True, help_text='Button text to be shown on Guidance and Support page', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='standardguidanceindexpage',
            name='button_link_text_es',
            field=models.CharField(blank=True, help_text='Button text to be shown on Guidance and Support page', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='standardguidanceindexpage',
            name='button_link_text_fr',
            field=models.CharField(blank=True, help_text='Button text to be shown on Guidance and Support page', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='standardguidanceindexpage',
            name='button_link_text_pt',
            field=models.CharField(blank=True, help_text='Button text to be shown on Guidance and Support page', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='standardguidanceindexpage',
            name='section_summary',
            field=models.TextField(blank=True, help_text='Summary seen on Guidance and Support page', null=True),
        ),
        migrations.AddField(
            model_name='standardguidanceindexpage',
            name='section_summary_en',
            field=models.TextField(blank=True, help_text='Summary seen on Guidance and Support page', null=True),
        ),
        migrations.AddField(
            model_name='standardguidanceindexpage',
            name='section_summary_es',
            field=models.TextField(blank=True, help_text='Summary seen on Guidance and Support page', null=True),
        ),
        migrations.AddField(
            model_name='standardguidanceindexpage',
            name='section_summary_fr',
            field=models.TextField(blank=True, help_text='Summary seen on Guidance and Support page', null=True),
        ),
        migrations.AddField(
            model_name='standardguidanceindexpage',
            name='section_summary_pt',
            field=models.TextField(blank=True, help_text='Summary seen on Guidance and Support page', null=True),
        ),
    ]
