# Generated by Django 2.2.12 on 2020-06-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_standard', '0005_auto_20200603_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencemenu',
            name='menu_type',
            field=models.CharField(default='ssot', help_text='The set of pages to which this menu belongs', max_length=255),
        ),
    ]
