# Generated by Django 2.2.9 on 2020-03-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_standard', '0006_activitystandardpage_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitystandardpage',
            name='menu_en',
            field=models.TextField(blank=True, help_text='HTML data for the page menu', null=True),
        ),
        migrations.AddField(
            model_name='activitystandardpage',
            name='menu_es',
            field=models.TextField(blank=True, help_text='HTML data for the page menu', null=True),
        ),
        migrations.AddField(
            model_name='activitystandardpage',
            name='menu_fr',
            field=models.TextField(blank=True, help_text='HTML data for the page menu', null=True),
        ),
        migrations.AddField(
            model_name='activitystandardpage',
            name='menu_pt',
            field=models.TextField(blank=True, help_text='HTML data for the page menu', null=True),
        ),
    ]
