# Generated by Django 2.2.9 on 2020-03-25 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati_standard', '0007_auto_20200320_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitystandardpage',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='activitystandardpage',
            name='menu_en',
        ),
        migrations.RemoveField(
            model_name='activitystandardpage',
            name='menu_es',
        ),
        migrations.RemoveField(
            model_name='activitystandardpage',
            name='menu_fr',
        ),
        migrations.RemoveField(
            model_name='activitystandardpage',
            name='menu_pt',
        ),
    ]
