# Generated by Django 2.2.12 on 2020-06-15 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtaildocs', '0010_document_file_hash'),
        ('iati_standard', '0007_auto_20200605_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document')),
                ('redirect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailredirects.Redirect')),
            ],
        ),
    ]
