# Generated by Django 2.2.12 on 2020-06-25 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati_standard', '0008_referencedownload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencemenu',
            options={'verbose_name_plural': 'reference menus'},
        ),
    ]
