# Generated by Django 2.2.9 on 2020-03-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_standard', '0008_auto_20200325_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='iatistandardpage',
            name='static',
            field=models.BooleanField(default=True, help_text='If true, retain static links. Otherwise use dynamic links.'),
        ),
    ]
