# Generated by Django 2.2.9 on 2020-03-26 14:03

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('iati_standard', '0009_iatistandardpage_static'),
    ]

    operations = [
        migrations.AddField(
            model_name='iatistandardpage',
            name='how_to_use_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='iatistandardpage',
            name='reference_cards',
            field=wagtail.core.fields.StreamField([('card', wagtail.core.blocks.StructBlock([('major_header', wagtail.core.blocks.CharBlock(help_text='Text for the header element of the card', required=False, template='iati_standard/blocks/major_header.html')), ('card_content', wagtail.core.blocks.StreamBlock([('minor_header', wagtail.core.blocks.CharBlock(icon='title', required=False, template='iati_standard/blocks/minor_header.html')), ('page_links', wagtail.core.blocks.StreamBlock([('page', wagtail.core.blocks.PageChooserBlock(required=False, template='iati_standard/blocks/page_link.html'))], template='iati_standard/blocks/page_links.html'))]))]))], blank=True, null=True),
        ),
    ]
