# Generated by Django 2.2.12 on 2020-06-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_standard', '0009_auto_20200625_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitystandardpage',
            name='meta_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='standardguidancepage',
            name='meta_order',
            field=models.IntegerField(default=0),
        ),
    ]
