# Generated by Django 2.2.12 on 2020-05-08 19:21

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('iati_standard', '0010_auto_20200326_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='iatistandardpage',
            name='guidance_parent_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='iatistandardpage',
            name='reference_cards',
            field=wagtail.core.fields.StreamField([('card', wagtail.core.blocks.StructBlock([('major_header', wagtail.core.blocks.CharBlock(help_text='Text for the header element of the card', required=False)), ('card_content', wagtail.core.blocks.StreamBlock([('minor_header', wagtail.core.blocks.CharBlock(icon='title', required=False, template='iati_standard/blocks/minor_header.html')), ('page_links', wagtail.core.blocks.StreamBlock([('page', wagtail.core.blocks.PageChooserBlock(required=False, template='iati_standard/blocks/page_link.html'))], template='iati_standard/blocks/page_links.html'))]))]))], blank=True, null=True),
        ),
    ]
