# Generated by Django 2.2.12 on 2020-05-08 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati_standard', '0011_auto_20200508_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitystandardpage',
            name='has_been_recursed',
        ),
    ]
