# Generated by Django 2.2.12 on 2020-07-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati_standard', '0011_auto_20200710_1354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReferenceDownload',
        ),
    ]
