# Generated by Django 2.2.13 on 2021-03-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_standard', '0012_delete_referencedownload'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncTaskResult',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.TextField(default='PENDING')),
                ('info', models.TextField(blank=True)),
            ],
        ),
    ]
