# Generated by Django 3.2.4 on 2021-08-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_standard', '0013_synctaskresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencemenu',
            name='menu_json',
            field=models.JSONField(),
        ),
    ]
