# Generated by Django 3.2.4 on 2022-05-22 07:13

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_social_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplepage',
            name='profile_content_editor',
            field=wagtail.fields.StreamField([('section_heading', wagtail.blocks.CharBlock(form_classname='title', icon='title')), ('paragraph', wagtail.blocks.CharBlock(icon='pilcrow')), ('rich_paragraph', wagtail.blocks.RichTextBlock(icon='pilcrow')), ('pullquote', wagtail.blocks.StructBlock([('quote', wagtail.blocks.TextBlock('quote title'))])), ('profile_editor', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(max_length=100, required=False)), ('profile_picture', wagtail.images.blocks.ImageChooserBlock(icon='image', label='Profile picture', required=False)), ('organisation_logo', wagtail.images.blocks.ImageChooserBlock(icon='image', label='Organisation logo', required=False)), ('organisation_name', wagtail.blocks.CharBlock(max_length=100, required=False)), ('IATI_role', wagtail.blocks.CharBlock(max_length=100, required=False)), ('external_role', wagtail.blocks.CharBlock(max_length=200, required=False)), ('description', wagtail.blocks.TextBlock(required=False)), ('IATI_constituency', wagtail.blocks.CharBlock(max_length=200, required=False))], icon='image'))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peoplepage',
            name='profile_content_editor_en',
            field=wagtail.fields.StreamField([('section_heading', wagtail.blocks.CharBlock(form_classname='title', icon='title')), ('paragraph', wagtail.blocks.CharBlock(icon='pilcrow')), ('rich_paragraph', wagtail.blocks.RichTextBlock(icon='pilcrow')), ('pullquote', wagtail.blocks.StructBlock([('quote', wagtail.blocks.TextBlock('quote title'))])), ('profile_editor', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(max_length=100, required=False)), ('profile_picture', wagtail.images.blocks.ImageChooserBlock(icon='image', label='Profile picture', required=False)), ('organisation_logo', wagtail.images.blocks.ImageChooserBlock(icon='image', label='Organisation logo', required=False)), ('organisation_name', wagtail.blocks.CharBlock(max_length=100, required=False)), ('IATI_role', wagtail.blocks.CharBlock(max_length=100, required=False)), ('external_role', wagtail.blocks.CharBlock(max_length=200, required=False)), ('description', wagtail.blocks.TextBlock(required=False)), ('IATI_constituency', wagtail.blocks.CharBlock(max_length=200, required=False))], icon='image'))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peoplepage',
            name='profile_content_editor_es',
            field=wagtail.fields.StreamField([('section_heading', wagtail.blocks.CharBlock(form_classname='title', icon='title')), ('paragraph', wagtail.blocks.CharBlock(icon='pilcrow')), ('rich_paragraph', wagtail.blocks.RichTextBlock(icon='pilcrow')), ('pullquote', wagtail.blocks.StructBlock([('quote', wagtail.blocks.TextBlock('quote title'))])), ('profile_editor', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(max_length=100, required=False)), ('profile_picture', wagtail.images.blocks.ImageChooserBlock(icon='image', label='Profile picture', required=False)), ('organisation_logo', wagtail.images.blocks.ImageChooserBlock(icon='image', label='Organisation logo', required=False)), ('organisation_name', wagtail.blocks.CharBlock(max_length=100, required=False)), ('IATI_role', wagtail.blocks.CharBlock(max_length=100, required=False)), ('external_role', wagtail.blocks.CharBlock(max_length=200, required=False)), ('description', wagtail.blocks.TextBlock(required=False)), ('IATI_constituency', wagtail.blocks.CharBlock(max_length=200, required=False))], icon='image'))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peoplepage',
            name='profile_content_editor_fr',
            field=wagtail.fields.StreamField([('section_heading', wagtail.blocks.CharBlock(form_classname='title', icon='title')), ('paragraph', wagtail.blocks.CharBlock(icon='pilcrow')), ('rich_paragraph', wagtail.blocks.RichTextBlock(icon='pilcrow')), ('pullquote', wagtail.blocks.StructBlock([('quote', wagtail.blocks.TextBlock('quote title'))])), ('profile_editor', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(max_length=100, required=False)), ('profile_picture', wagtail.images.blocks.ImageChooserBlock(icon='image', label='Profile picture', required=False)), ('organisation_logo', wagtail.images.blocks.ImageChooserBlock(icon='image', label='Organisation logo', required=False)), ('organisation_name', wagtail.blocks.CharBlock(max_length=100, required=False)), ('IATI_role', wagtail.blocks.CharBlock(max_length=100, required=False)), ('external_role', wagtail.blocks.CharBlock(max_length=200, required=False)), ('description', wagtail.blocks.TextBlock(required=False)), ('IATI_constituency', wagtail.blocks.CharBlock(max_length=200, required=False))], icon='image'))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peoplepage',
            name='profile_content_editor_pt',
            field=wagtail.fields.StreamField([('section_heading', wagtail.blocks.CharBlock(form_classname='title', icon='title')), ('paragraph', wagtail.blocks.CharBlock(icon='pilcrow')), ('rich_paragraph', wagtail.blocks.RichTextBlock(icon='pilcrow')), ('pullquote', wagtail.blocks.StructBlock([('quote', wagtail.blocks.TextBlock('quote title'))])), ('profile_editor', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(max_length=100, required=False)), ('profile_picture', wagtail.images.blocks.ImageChooserBlock(icon='image', label='Profile picture', required=False)), ('organisation_logo', wagtail.images.blocks.ImageChooserBlock(icon='image', label='Organisation logo', required=False)), ('organisation_name', wagtail.blocks.CharBlock(max_length=100, required=False)), ('IATI_role', wagtail.blocks.CharBlock(max_length=100, required=False)), ('external_role', wagtail.blocks.CharBlock(max_length=200, required=False)), ('description', wagtail.blocks.TextBlock(required=False)), ('IATI_constituency', wagtail.blocks.CharBlock(max_length=200, required=False))], icon='image'))], blank=True, null=True),
        ),
    ]
