# Generated by Django 2.2.9 on 2020-04-03 13:56

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0002_auto_20200225_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getinvolvedpage',
            name='highlight',
            field=wagtail.core.fields.StreamField([('highlight', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(icon='title')), ('description', wagtail.core.blocks.CharBlock(icon='pilcrow')), ('page', wagtail.core.blocks.PageChooserBlock(icon='link')), ('link_label', wagtail.core.blocks.CharBlock(icon='link'))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='getinvolvedpage',
            name='highlight_en',
            field=wagtail.core.fields.StreamField([('highlight', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(icon='title')), ('description', wagtail.core.blocks.CharBlock(icon='pilcrow')), ('page', wagtail.core.blocks.PageChooserBlock(icon='link')), ('link_label', wagtail.core.blocks.CharBlock(icon='link'))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='getinvolvedpage',
            name='highlight_es',
            field=wagtail.core.fields.StreamField([('highlight', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(icon='title')), ('description', wagtail.core.blocks.CharBlock(icon='pilcrow')), ('page', wagtail.core.blocks.PageChooserBlock(icon='link')), ('link_label', wagtail.core.blocks.CharBlock(icon='link'))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='getinvolvedpage',
            name='highlight_fr',
            field=wagtail.core.fields.StreamField([('highlight', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(icon='title')), ('description', wagtail.core.blocks.CharBlock(icon='pilcrow')), ('page', wagtail.core.blocks.PageChooserBlock(icon='link')), ('link_label', wagtail.core.blocks.CharBlock(icon='link'))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='getinvolvedpage',
            name='highlight_pt',
            field=wagtail.core.fields.StreamField([('highlight', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(icon='title')), ('description', wagtail.core.blocks.CharBlock(icon='pilcrow')), ('page', wagtail.core.blocks.PageChooserBlock(icon='link')), ('link_label', wagtail.core.blocks.CharBlock(icon='link'))]))], blank=True, null=True),
        ),
    ]
