# Generated by Django 3.2.4 on 2023-01-20 14:56

from django.db import migrations
import home.models
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0005_auto_20220804_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getinvolvedpage',
            name='content_editor',
            field=wagtail.fields.StreamField([('h2', wagtail.blocks.CharBlock(form_classname='title', icon='title')), ('h3', wagtail.blocks.CharBlock(form_classname='title', icon='title')), ('h4', wagtail.blocks.CharBlock(form_classname='title', icon='title')), ('intro', wagtail.blocks.RichTextBlock(icon='pilcrow')), ('paragraph', wagtail.blocks.RichTextBlock(icon='pilcrow')), ('image_figure', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('alignment', home.models.ImageAlignmentChoiceBlock()), ('caption', wagtail.blocks.RichTextBlock(required=False))], icon='image', label='Image figure')), ('pullquote', wagtail.blocks.StructBlock([('quote', wagtail.blocks.TextBlock('quote title'))])), ('aligned_html', wagtail.blocks.StructBlock([('html', wagtail.blocks.RawHTMLBlock()), ('alignment', home.models.HTMLAlignmentChoiceBlock())], icon='code', label='Raw HTML')), ('document_box', wagtail.blocks.StreamBlock([('document_box_heading', wagtail.blocks.CharBlock(form_classname='title', help_text='Only one heading per box.', icon='title', required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(icon='doc-full-inverse', required=False))], icon='doc-full-inverse')), ('anchor_point', wagtail.blocks.CharBlock(help_text='Custom anchor points are expected to precede other content.', icon='order-down')), ('fast_youtube_embed', wagtail.blocks.URLBlock(icon='code', label='Fast YouTube Embed'))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='getinvolvedpage',
            name='content_editor_en',
            field=wagtail.fields.StreamField([('h2', wagtail.blocks.CharBlock(form_classname='title', icon='title')), ('h3', wagtail.blocks.CharBlock(form_classname='title', icon='title')), ('h4', wagtail.blocks.CharBlock(form_classname='title', icon='title')), ('intro', wagtail.blocks.RichTextBlock(icon='pilcrow')), ('paragraph', wagtail.blocks.RichTextBlock(icon='pilcrow')), ('image_figure', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('alignment', home.models.ImageAlignmentChoiceBlock()), ('caption', wagtail.blocks.RichTextBlock(required=False))], icon='image', label='Image figure')), ('pullquote', wagtail.blocks.StructBlock([('quote', wagtail.blocks.TextBlock('quote title'))])), ('aligned_html', wagtail.blocks.StructBlock([('html', wagtail.blocks.RawHTMLBlock()), ('alignment', home.models.HTMLAlignmentChoiceBlock())], icon='code', label='Raw HTML')), ('document_box', wagtail.blocks.StreamBlock([('document_box_heading', wagtail.blocks.CharBlock(form_classname='title', help_text='Only one heading per box.', icon='title', required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(icon='doc-full-inverse', required=False))], icon='doc-full-inverse')), ('anchor_point', wagtail.blocks.CharBlock(help_text='Custom anchor points are expected to precede other content.', icon='order-down')), ('fast_youtube_embed', wagtail.blocks.URLBlock(icon='code', label='Fast YouTube Embed'))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='getinvolvedpage',
            name='content_editor_es',
            field=wagtail.fields.StreamField([('h2', wagtail.blocks.CharBlock(form_classname='title', icon='title')), ('h3', wagtail.blocks.CharBlock(form_classname='title', icon='title')), ('h4', wagtail.blocks.CharBlock(form_classname='title', icon='title')), ('intro', wagtail.blocks.RichTextBlock(icon='pilcrow')), ('paragraph', wagtail.blocks.RichTextBlock(icon='pilcrow')), ('image_figure', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('alignment', home.models.ImageAlignmentChoiceBlock()), ('caption', wagtail.blocks.RichTextBlock(required=False))], icon='image', label='Image figure')), ('pullquote', wagtail.blocks.StructBlock([('quote', wagtail.blocks.TextBlock('quote title'))])), ('aligned_html', wagtail.blocks.StructBlock([('html', wagtail.blocks.RawHTMLBlock()), ('alignment', home.models.HTMLAlignmentChoiceBlock())], icon='code', label='Raw HTML')), ('document_box', wagtail.blocks.StreamBlock([('document_box_heading', wagtail.blocks.CharBlock(form_classname='title', help_text='Only one heading per box.', icon='title', required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(icon='doc-full-inverse', required=False))], icon='doc-full-inverse')), ('anchor_point', wagtail.blocks.CharBlock(help_text='Custom anchor points are expected to precede other content.', icon='order-down')), ('fast_youtube_embed', wagtail.blocks.URLBlock(icon='code', label='Fast YouTube Embed'))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='getinvolvedpage',
            name='content_editor_fr',
            field=wagtail.fields.StreamField([('h2', wagtail.blocks.CharBlock(form_classname='title', icon='title')), ('h3', wagtail.blocks.CharBlock(form_classname='title', icon='title')), ('h4', wagtail.blocks.CharBlock(form_classname='title', icon='title')), ('intro', wagtail.blocks.RichTextBlock(icon='pilcrow')), ('paragraph', wagtail.blocks.RichTextBlock(icon='pilcrow')), ('image_figure', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('alignment', home.models.ImageAlignmentChoiceBlock()), ('caption', wagtail.blocks.RichTextBlock(required=False))], icon='image', label='Image figure')), ('pullquote', wagtail.blocks.StructBlock([('quote', wagtail.blocks.TextBlock('quote title'))])), ('aligned_html', wagtail.blocks.StructBlock([('html', wagtail.blocks.RawHTMLBlock()), ('alignment', home.models.HTMLAlignmentChoiceBlock())], icon='code', label='Raw HTML')), ('document_box', wagtail.blocks.StreamBlock([('document_box_heading', wagtail.blocks.CharBlock(form_classname='title', help_text='Only one heading per box.', icon='title', required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(icon='doc-full-inverse', required=False))], icon='doc-full-inverse')), ('anchor_point', wagtail.blocks.CharBlock(help_text='Custom anchor points are expected to precede other content.', icon='order-down')), ('fast_youtube_embed', wagtail.blocks.URLBlock(icon='code', label='Fast YouTube Embed'))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='getinvolvedpage',
            name='content_editor_pt',
            field=wagtail.fields.StreamField([('h2', wagtail.blocks.CharBlock(form_classname='title', icon='title')), ('h3', wagtail.blocks.CharBlock(form_classname='title', icon='title')), ('h4', wagtail.blocks.CharBlock(form_classname='title', icon='title')), ('intro', wagtail.blocks.RichTextBlock(icon='pilcrow')), ('paragraph', wagtail.blocks.RichTextBlock(icon='pilcrow')), ('image_figure', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('alignment', home.models.ImageAlignmentChoiceBlock()), ('caption', wagtail.blocks.RichTextBlock(required=False))], icon='image', label='Image figure')), ('pullquote', wagtail.blocks.StructBlock([('quote', wagtail.blocks.TextBlock('quote title'))])), ('aligned_html', wagtail.blocks.StructBlock([('html', wagtail.blocks.RawHTMLBlock()), ('alignment', home.models.HTMLAlignmentChoiceBlock())], icon='code', label='Raw HTML')), ('document_box', wagtail.blocks.StreamBlock([('document_box_heading', wagtail.blocks.CharBlock(form_classname='title', help_text='Only one heading per box.', icon='title', required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(icon='doc-full-inverse', required=False))], icon='doc-full-inverse')), ('anchor_point', wagtail.blocks.CharBlock(help_text='Custom anchor points are expected to precede other content.', icon='order-down')), ('fast_youtube_embed', wagtail.blocks.URLBlock(icon='code', label='Fast YouTube Embed'))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='getinvolvedpage',
            name='highlight',
            field=wagtail.fields.StreamField([('highlight', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title')), ('description', wagtail.blocks.CharBlock(icon='pilcrow')), ('page', wagtail.blocks.PageChooserBlock(icon='link')), ('link_label', wagtail.blocks.CharBlock(icon='link'))]))], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='getinvolvedpage',
            name='highlight_en',
            field=wagtail.fields.StreamField([('highlight', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title')), ('description', wagtail.blocks.CharBlock(icon='pilcrow')), ('page', wagtail.blocks.PageChooserBlock(icon='link')), ('link_label', wagtail.blocks.CharBlock(icon='link'))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='getinvolvedpage',
            name='highlight_es',
            field=wagtail.fields.StreamField([('highlight', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title')), ('description', wagtail.blocks.CharBlock(icon='pilcrow')), ('page', wagtail.blocks.PageChooserBlock(icon='link')), ('link_label', wagtail.blocks.CharBlock(icon='link'))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='getinvolvedpage',
            name='highlight_fr',
            field=wagtail.fields.StreamField([('highlight', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title')), ('description', wagtail.blocks.CharBlock(icon='pilcrow')), ('page', wagtail.blocks.PageChooserBlock(icon='link')), ('link_label', wagtail.blocks.CharBlock(icon='link'))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='getinvolvedpage',
            name='highlight_pt',
            field=wagtail.fields.StreamField([('highlight', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(icon='title')), ('description', wagtail.blocks.CharBlock(icon='pilcrow')), ('page', wagtail.blocks.PageChooserBlock(icon='link')), ('link_label', wagtail.blocks.CharBlock(icon='link'))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
