# Generated by Django 2.0.5 on 2018-06-26 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about', '0002_auto_20180626_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsingDataPage',
            fields=[
                ('aboutpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='about.AboutPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('about.aboutpage',),
        ),
    ]
