# Generated by Django 2.0.5 on 2018-08-30 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('using_data', '0003_auto_20180828_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='usingdatapage',
            name='quote_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usingdatapage',
            name='quote_name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usingdatapage',
            name='quote_name_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usingdatapage',
            name='quote_name_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usingdatapage',
            name='quote_name_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usingdatapage',
            name='quote_portrait',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='usingdatapage',
            name='quote_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usingdatapage',
            name='quote_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usingdatapage',
            name='quote_text_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usingdatapage',
            name='quote_text_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usingdatapage',
            name='quote_text_pt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
