# Generated by Django 2.2.9 on 2020-04-03 14:41

from django.db import migrations
from importlib import import_module

DATA = {
    'title': 'Search iatistandard.org',
    'title_en': 'Search iatistandard.org',
    'title_fr': 'Recherche iatistandard.org',
    'slug': 'search',
    'slug_en': 'search',
    'slug_fr': 'search',
    'heading': 'Search iatistandard.org',
    'heading_en': 'Search iatistandard.org',
    'heading_fr': 'Recherche iatistandard.org',
}


class Migration(migrations.Migration):

    def add_search_page(apps, schema_editor):
        """Add a new search page with minimal data"""
        # if the models no longer exists, return directly
        try:
            HomePage = import_module('home.models').HomePage
            SearchPage = import_module('search.models').SearchPage
        except Exception:
            return

        # return if we already have a search page
        if SearchPage.objects.all().first():
            return

        parent = HomePage.objects.all().first()
        new_page = SearchPage()
        for field, value in DATA.items():
            if hasattr(new_page, field):
                setattr(new_page, field, value)

        parent.add_child(instance=new_page)
        new_page.save_revision()

    dependencies = [
        ('search', '0003_add_search_page'),
    ]

    operations = [
        migrations.RunPython(add_search_page),
    ]
