# Generated by Django 3.2.4 on 2021-08-27 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20200403_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchpage',
            name='excerpt_en',
        ),
        migrations.RemoveField(
            model_name='searchpage',
            name='excerpt_es',
        ),
        migrations.RemoveField(
            model_name='searchpage',
            name='excerpt_fr',
        ),
        migrations.RemoveField(
            model_name='searchpage',
            name='excerpt_pt',
        ),
        migrations.RemoveField(
            model_name='searchpage',
            name='heading_en',
        ),
        migrations.RemoveField(
            model_name='searchpage',
            name='heading_es',
        ),
        migrations.RemoveField(
            model_name='searchpage',
            name='heading_fr',
        ),
        migrations.RemoveField(
            model_name='searchpage',
            name='heading_pt',
        ),
    ]
