# Generated by Django 2.2.9 on 2020-02-14 14:23

from django.db import migrations, models
import django.db.models.deletion
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(help_text='The quote for the testimonial')),
                ('quote_en', models.TextField(help_text='The quote for the testimonial', null=True)),
                ('quote_fr', models.TextField(help_text='The quote for the testimonial', null=True)),
                ('quote_es', models.TextField(help_text='The quote for the testimonial', null=True)),
                ('quote_pt', models.TextField(help_text='The quote for the testimonial', null=True)),
                ('quotee', models.CharField(help_text='The source of the quote', max_length=255)),
                ('quotee_en', models.CharField(help_text='The source of the quote', max_length=255, null=True)),
                ('quotee_fr', models.CharField(help_text='The source of the quote', max_length=255, null=True)),
                ('quotee_es', models.CharField(help_text='The source of the quote', max_length=255, null=True)),
                ('quotee_pt', models.CharField(help_text='The source of the quote', max_length=255, null=True)),
                ('image', models.ForeignKey(blank=True, help_text='Optional: image for the quotee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'ordering': ['quotee'],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
