# Generated by Django 2.2.9 on 2020-02-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='quote',
            field=models.CharField(help_text='The quote for the testimonial', max_length=255),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='quote_en',
            field=models.CharField(help_text='The quote for the testimonial', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='quote_es',
            field=models.CharField(help_text='The quote for the testimonial', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='quote_fr',
            field=models.CharField(help_text='The quote for the testimonial', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='quote_pt',
            field=models.CharField(help_text='The quote for the testimonial', max_length=255, null=True),
        ),
    ]
