# Generated by Django 3.2.4 on 2021-08-27 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0003_auto_20200220_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='quote_en',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='quote_es',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='quote_fr',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='quote_pt',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='quotee_en',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='quotee_es',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='quotee_fr',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='quotee_pt',
        ),
    ]
