# Generated by Django 2.2.9 on 2020-01-28 14:47

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarymenulinks',
            name='meganav',
            field=wagtail.core.fields.StreamField([('type_a', wagtail.core.blocks.StructBlock([('highlight', wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock(help_text='Highlighted page')), ('description_en', wagtail.core.blocks.TextBlock(help_text='Description for the highlight module', label='Description [en]')), ('description_fr', wagtail.core.blocks.TextBlock(help_text='Description for the highlight module', label='Description [fr]', required=False))], help_text='\n                  <strong>Highlight module.</strong><br>\n                  Internal page link and short description.\n                  ')), ('columns', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('use_first_page_as_title', wagtail.core.blocks.BooleanBlock(help_text='Optional: if checked, the first page in the list will be displayed as a title', required=False)), ('title_en', wagtail.core.blocks.CharBlock(help_text='Optional: plain text title for the page list', label='Title [en]', required=False)), ('title_fr', wagtail.core.blocks.CharBlock(help_text='Optional: plain text title for the page list', label='Title [fr]', required=False)), ('description_en', wagtail.core.blocks.CharBlock(help_text='Optional: description for the page list', label='Description [en]', required=False)), ('description_fr', wagtail.core.blocks.CharBlock(help_text='Optional: description for the page list', label='Description [fr]', required=False)), ('page_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock())])))], label='Page list')))]))], blank=True),
        ),
    ]
