# Generated by Django 2.0.12 on 2019-12-18 15:35

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolslistingpage',
            name='highlight_content',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional: content for the highlight panel displayed after featured tools'),
        ),
        migrations.AlterField(
            model_name='toolslistingpage',
            name='highlight_content_en',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional: content for the highlight panel displayed after featured tools', null=True),
        ),
        migrations.AlterField(
            model_name='toolslistingpage',
            name='highlight_content_es',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional: content for the highlight panel displayed after featured tools', null=True),
        ),
        migrations.AlterField(
            model_name='toolslistingpage',
            name='highlight_content_fr',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional: content for the highlight panel displayed after featured tools', null=True),
        ),
        migrations.AlterField(
            model_name='toolslistingpage',
            name='highlight_content_pt',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional: content for the highlight panel displayed after featured tools', null=True),
        ),
    ]
