# Generated by Django 2.2.9 on 2020-03-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_toolsubpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsubpage',
            name='listing_description',
            field=models.CharField(blank=True, help_text='Optional: short description to appear on the listing page if this tool is featured', max_length=255),
        ),
        migrations.AddField(
            model_name='toolsubpage',
            name='listing_description_en',
            field=models.CharField(blank=True, help_text='Optional: short description to appear on the listing page if this tool is featured', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='toolsubpage',
            name='listing_description_es',
            field=models.CharField(blank=True, help_text='Optional: short description to appear on the listing page if this tool is featured', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='toolsubpage',
            name='listing_description_fr',
            field=models.CharField(blank=True, help_text='Optional: short description to appear on the listing page if this tool is featured', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='toolsubpage',
            name='listing_description_pt',
            field=models.CharField(blank=True, help_text='Optional: short description to appear on the listing page if this tool is featured', max_length=255, null=True),
        ),
    ]
