# Generated by Django 3.2.4 on 2023-02-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_auto_20230120_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolpage',
            name='button_label',
            field=models.CharField(blank=True, help_text='Optional: label for the external URL button', max_length=999),
        ),
        migrations.AlterField(
            model_name='toolpage',
            name='button_label_en',
            field=models.CharField(blank=True, help_text='Optional: label for the external URL button', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='toolpage',
            name='button_label_es',
            field=models.CharField(blank=True, help_text='Optional: label for the external URL button', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='toolpage',
            name='button_label_fr',
            field=models.CharField(blank=True, help_text='Optional: label for the external URL button', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='toolpage',
            name='button_label_pt',
            field=models.CharField(blank=True, help_text='Optional: label for the external URL button', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='toolpage',
            name='external_url',
            field=models.URLField(blank=True, help_text='Optional: external URL of the tool', max_length=999),
        ),
        migrations.AlterField(
            model_name='toolpage',
            name='listing_description',
            field=models.CharField(blank=True, help_text='Optional: short description to appear on the listing page if this tool is featured', max_length=999),
        ),
        migrations.AlterField(
            model_name='toolpage',
            name='listing_description_en',
            field=models.CharField(blank=True, help_text='Optional: short description to appear on the listing page if this tool is featured', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='toolpage',
            name='listing_description_es',
            field=models.CharField(blank=True, help_text='Optional: short description to appear on the listing page if this tool is featured', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='toolpage',
            name='listing_description_fr',
            field=models.CharField(blank=True, help_text='Optional: short description to appear on the listing page if this tool is featured', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='toolpage',
            name='listing_description_pt',
            field=models.CharField(blank=True, help_text='Optional: short description to appear on the listing page if this tool is featured', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='toolsubpage',
            name='button_label',
            field=models.CharField(blank=True, help_text='Optional: label for the external URL button', max_length=999),
        ),
        migrations.AlterField(
            model_name='toolsubpage',
            name='button_label_en',
            field=models.CharField(blank=True, help_text='Optional: label for the external URL button', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='toolsubpage',
            name='button_label_es',
            field=models.CharField(blank=True, help_text='Optional: label for the external URL button', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='toolsubpage',
            name='button_label_fr',
            field=models.CharField(blank=True, help_text='Optional: label for the external URL button', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='toolsubpage',
            name='button_label_pt',
            field=models.CharField(blank=True, help_text='Optional: label for the external URL button', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='toolsubpage',
            name='external_url',
            field=models.URLField(blank=True, help_text='Optional: external URL of the tool', max_length=999),
        ),
        migrations.AlterField(
            model_name='toolsubpage',
            name='listing_description',
            field=models.CharField(blank=True, help_text='Optional: short description to appear on the listing page if this tool is featured', max_length=999),
        ),
        migrations.AlterField(
            model_name='toolsubpage',
            name='listing_description_en',
            field=models.CharField(blank=True, help_text='Optional: short description to appear on the listing page if this tool is featured', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='toolsubpage',
            name='listing_description_es',
            field=models.CharField(blank=True, help_text='Optional: short description to appear on the listing page if this tool is featured', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='toolsubpage',
            name='listing_description_fr',
            field=models.CharField(blank=True, help_text='Optional: short description to appear on the listing page if this tool is featured', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='toolsubpage',
            name='listing_description_pt',
            field=models.CharField(blank=True, help_text='Optional: short description to appear on the listing page if this tool is featured', max_length=999, null=True),
        ),
    ]
