name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master/develop branches
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup docker-compose
        run: |
          docker-compose build
          docker-compose up -d
          while ! echo exit | nc localhost 5000; do sleep 10; done
      - name: flake8 lint
        run: docker-compose exec web make flake8
      - name: pylint
        run: docker-compose exec web make pylint
      - name: pydocstyle lint
        run: docker-compose exec web make pydocstyle
      - name: pytest
        run: docker-compose exec web make test
